name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    outputs:
      stdout: ${{ steps.uncolored-stdout.outputs.stdout }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup yarn
        run: npm install -g yarn

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Run Test
        uses: mathiasvr/command-output@v1
        id: run
        with:
          run: yarn test
      - name: Remove ANSI color escape sequences
        uses: marcransome/remove-ansi-colors@v1
        id: remove-ansi-colors
        with:
          colored: ${{ steps.run.outputs.stderr }}
      - name: Use uncolored output
        id: uncolored-stdout
        run: echo "${{ steps.remove-ansi-colors.outputs.uncolored }}"

  comment-on-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    name: Comment on PR
    needs: test
    if: failure()
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            :warning: **Test failed**
            - [Job log](${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }})
            ```bash
            ${{ needs.test.outputs.error }}
            ```
