name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup yarn
        run: npm install -g yarn

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Run tests
        id: test
        run: yarn test

      - name: Comment PR
        if: always() && steps.test.outcome == 'failure'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            :warning: **Test failed**
            - [Job log](${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }})
            - [Test log](${{ steps.test.outputs.run_id }})
            ```bash
            ${{ steps.test.outputs.error }}
            ```
